# change the followings to match your Github username and repo name
baseurl: "/website" # the name of your github repo
url: "https://taskday.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Taskday: manage your day as you want"
description: A free and open source issues and project management software

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Satoshi Nakamoto
author-bio: Creator of Bitcoin  # change to false to hide
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/giorgiopogliani
facebook: false
instagram: false
github: https://github.com/taskday
linkedin: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: ""
footer-msg-link: false

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
